### PR TITLE
Updates to support building on windows (and testing out stunnel FIPS packages)

### PR DESCRIPTION
**Pull request by tyler-ball**
\cc @tylercloke @rmoshier @ElizabethU @dmccown

### CODE REVIEW

**Comment by schisamo** [comment]
Are we shipping a separate `chef-fips` package? I thought the plan was to ship everything in the existing `chef` (and `chefdk`) packages?

**Comment by tyler-ball** [comment]
@schisamo We are not planning on shipping a separate `chef-fips` package. But we have been using this for testing (since it is much faster to build this instead of the ChefDK or Chef Server).  This PR was updates I made to support building on Windows.

Having said all that, I could definitely update the README to show that the future of this repo is uncertain. Or we could just decide to delete it now. Thoughts @dmccown @tylercloke @rmoshier @ElizabethU ?

**Comment by rmoshier** [comment]
I'm not sure how much we are going to need it for testing this week, so maybe we update the README now and delete the repo at the end of the FIPS work?

**Comment by dmccown** [comment]
So all the work in this repo is just to prove out what we are going to do for other products?

**Pull request merged**
